version: '3'
services:
    web:
        container_name: asmbb_ubuntu
        #privileged: true
        build: ./server
        #volumes:
        #    - "./www:/home/work/_app/nginx/html"
        ports:
            - "80:80"
            - "443:443"
        #command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        #restart: always
        #cap_add:
            #- SYS_ADMIN
        security_opt:
            #- seccomp:unconfined
            - seccomp:"./server/patch.json"
        command: [ "/bin/sh", "-c", "/home/entry.sh && tail -f /dev/null" ]